### ISSUE TITLE
InvalidSetType error if the queried item has an attribute of type String Set

### ISSUE THREAD

**Issue by Sachin-Radhakrishnan** [typedorm/typedorm#157]
When i queried for the following item using findOne API ,it is failing with an InvalidSetType exception

DynamoDB JSON
==============
```json
{
  "PK": {
    "S": "entity#123"
  },
  "SK": {
    "S": "root"
  },
  "stringset": {
    "SS": [
      "test"
    ]
  }
}

```
Lambda Stack trace
===============
```
{
    "errorType": "InvalidSetType",
    "errorMessage": "Sets can contain string, number, or binary values",
    "code": "InvalidSetType",
    "message": "Sets can contain string, number, or binary values",
    "time": "2021-08-02T06:15:53.376Z",
    "stack": [
        "InvalidSetType: Sets can contain string, number, or binary values",
        "    at Set.detectType (/var/runtime/node_modules/aws-sdk/lib/dynamodb/set.js:37:24)",
        "    at Set.initialize (/var/runtime/node_modules/aws-sdk/lib/dynamodb/set.js:28:10)",
        "    at new Set (/var/runtime/node_modules/aws-sdk/lib/dynamodb/set.js:22:10)",
        "    at TransformOperationExecutor.transform (/var/task/node_modules/class-transformer/cjs/TransformOperationExecutor.js:138:32)",
        "    at TransformOperationExecutor.transform (/var/task/node_modules/class-transformer/cjs/TransformOperationExecutor.js:277:47)",
        "    at ClassTransformer.plainToClassFromExist (/var/task/node_modules/class-transformer/cjs/ClassTransformer.js:34:25)",
        "    at Object.plainToClassFromExist (/var/task/node_modules/class-transformer/cjs/index.js:34:29)",
        "    at EntityTransformer.fromDynamoEntity (/var/task/node_modules/@typedorm/core/src/classes/transformer/entity-transformer.js:65:59)",
        "    at EntityManager.<anonymous> (/var/task/node_modules/@typedorm/core/src/classes/manager/entity-manager.js:113:56)",
        "    at Generator.next (<anonymous>)"
    ]
}
```

**Comment by whimzyLive** [comment]
@Sachin-Radhakrishnan Can I see what the entity declaration looks like for a given DynamoDB JSON?

**Comment by Sachin-Radhakrishnan** [comment]
That String Set is actually not a part of our entity class.It is an unused attribute in the item. I am also sharing the library logs for your info

Query
============================================
 let res1 = await getEntityManager().find(
            EntityData,
            "test-entity@gmail.com",
            {
                queryIndex: process.env.USER_V2_EMAIL_INDEX!,
                limit: 1
            })
Entity
============================================
import { Entity, INDEX_TYPE, Attribute } from "@typedorm/common";
import { v4 as uuidv4 } from 'uuid'

@Entity({
    name: 'sample-entity',
    primaryKey: {
        partitionKey: 'en#' + uuidv4(),
        sortKey: 'root',
    },
    indexes: {
        [process.env.EMAIL_INDEX!]: {
            type: INDEX_TYPE.GSI,
            partitionKey: '{{email}}',
            sortKey: ""
        }
    }
})
export default class EntityData {

    @Attribute()
    name!: string;

    @Attribute()
    email!: string;
}

Library Logs
==============================================
2021-08-02T15:11:14.035Z typedorm:transform:log b5ae7ecc-983c-476e-9871-bedde6c70105 QUERY sample-entity Before: 
Primary key:  test-entity@gmail.com 
Options:  
{
  "queryIndex": "email-index-v2",
  "limit": 1
}

2021-08-02T15:11:14.035Z typedorm:transform:log b5ae7ecc-983c-476e-9871-bedde6c70105 QUERY sample-entity After: 
Primary key:  test-entity@gmail.com 
Body:  
{
  "TableName": "user-v2",
  "IndexName": "email-index-v2",
  "Limit": 1,
  "ScanIndexForward": true,
  "KeyConditionExpression": "#KY_CE_email = :KY_CE_email",
  "ExpressionAttributeNames": {
    "#KY_CE_email": "email"
  },
  "ExpressionAttributeValues": {
    ":KY_CE_email": "test-entity@gmail.com"
  }
}

2021-08-02T15:11:14.174Z typedorm:transform:log b5ae7ecc-983c-476e-9871-bedde6c70105 RESPONSE sample-entity Before: 
Body:  
{
  "SK": "root",
  "stringset": [
    "test"
  ],
  "email": "test-entity@gmail.com",
  "PK": "entity#12345678",
  "name": "ABCD"
}

2021-08-02T15:11:14.174Z	e582e965-da72-494a-a765-1cab0153ca12	ERROR	Invoke Error 	{"errorType":"InvalidSetType","errorMessage":"Sets can contain string, number, or binary values","code":"InvalidSetType","message":"Sets can contain string, number, or binary values","time":"2021-08-02T15:11:14.174Z","stack":["InvalidSetType: Sets can contain string, number, or binary values","    at Set.detectType (/var/runtime/node_modules/aws-sdk/lib/dynamodb/set.js:37:24)","    at Set.initialize (/var/runtime/node_modules/aws-sdk/lib/dynamodb/set.js:28:10)","    at new Set (/var/runtime/node_modules/aws-sdk/lib/dynamodb/set.js:22:10)","    at TransformOperationExecutor.transform (/var/task/node_modules/class-transformer/cjs/TransformOperationExecutor.js:138:32)","    at TransformOperationExecutor.transform (/var/task/node_modules/class-transformer/cjs/TransformOperationExecutor.js:277:47)","    at ClassTransformer.plainToClassFromExist (/var/task/node_modules/class-transformer/cjs/ClassTransformer.js:34:25)","    at Object.plainToClassFromExist (/var/task/node_modules/class-transformer/cjs/index.js:34:29)","    at EntityTransformer.fromDynamoEntity (/var/task/node_modules/@typedorm/core/src/classes/transformer/entity-transformer.js:65:59)","    at /var/task/node_modules/@typedorm/core/src/classes/manager/entity-manager.js:303:127","    at Array.map (<anonymous>)"]}

**Comment by whimzyLive** [comment]
@Sachin-Radhakrishnan I could not replicate the above issue. It seems to work without any issues, 

can you try with the latest version of `TypeDORM` and `aws-sdk` and let me know if the issue is still there?

**Comment by Sachin-Radhakrishnan** [comment]
@whimzyLive Wrote a mock test like what you did. In that mock test, it is working fine, but when I run the original code in AWS Lambda and while fetching the record from dynamodb I am getting this issue frequently.

**Comment by Sachin-Radhakrishnan** [comment]
@whimzyLive I think this happens when "class-transformer" lib  tries to create dynamodb string set with no initial values via reflection.

Reference: https://github.com/aws/aws-sdk-js/issues/3235.

**Comment by whimzyLive** [comment]
@Sachin-Radhakrishnan That makes sense. But since I can't reproduce it I don't know how to help you. If you can provide me a repro of some kind, I have a look into it this weekend. 

Maybe using something like [this](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started-hello-world.html), so that I can step through the parsing logic to find out what's actually happening.

**Comment by whimzyLive** [comment]
@meeech Thanks for the repro and other details. Fix is on the way.
