### ISSUE TITLE
Error resolving module: possibly due to webpack

### ISSUE THREAD

**Issue by mishabruml** [typedorm/typedorm#201]
Trying to run this lib from a lambda function within a monorepo. For context, none of the other node modules I have used in this project fail to load. 

```shell
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module '@typedorm/core/public-api'",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '@typedorm/core/public-api'",
        "    at _loadUserApp (/var/runtime/UserFunction.js:202:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:242:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
        "    at Module.load (internal/modules/cjs/loader.js:950:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```

**Comment by mishabruml** [comment]
I've been working more on this. I found some warning logs from webpack that may give a clue

```shell
WARNING in ../../node_modules/@typedorm/core/src/helpers/get-unique-request-id.js 3:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ../../node_modules/@typedorm/core/src/classes/manager/batch-manager.js
 @ ../../node_modules/@typedorm/core/public-api.js
 @ ./src/handlers/hello/index.ts 11:21-57

WARNING in ../../node_modules/@typedorm/core/src/helpers/handle-transaction-result.js 3:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ../../node_modules/@typedorm/core/src/classes/manager/transaction-manager.js
 @ ../../node_modules/@typedorm/core/public-api.js
 @ ./src/handlers/hello/index.ts 11:21-57

WARNING in ../../node_modules/@typedorm/core/src/helpers/is-dynamo-entity-key-schema.js 3:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ../../node_modules/@typedorm/core/src/classes/transformer/base-transformer.js
 @ ../../node_modules/@typedorm/core/src/classes/transformer/entity-transformer.js
 @ ../../node_modules/@typedorm/core/src/classes/manager/entity-manager.js
 @ ../../node_modules/@typedorm/core/public-api.js
 @ ./src/handlers/hello/index.ts 11:21-57

WARNING in ../../node_modules/@typedorm/core/src/helpers/is-empty-object.js 3:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ../../node_modules/@typedorm/core/src/classes/manager/batch-manager.js
 @ ../../node_modules/@typedorm/core/public-api.js
 @ ./src/handlers/hello/index.ts 11:21-57

WARNING in ../../node_modules/@typedorm/core/src/helpers/is-key-of-type-alias-schema.js 3:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ../../node_modules/@typedorm/core/src/helpers/get-interpolated-keys.js
 @ ../../node_modules/@typedorm/core/src/helpers/is-used-for-primary-key.js
 @ ../../node_modules/@typedorm/core/src/classes/connection/connection.js
 @ ../../node_modules/@typedorm/core/public-api.js
 @ ./src/handlers/hello/index.ts 11:21-57

WARNING in ../../node_modules/@typedorm/core/src/helpers/is-object.js 3:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ../../node_modules/@typedorm/core/src/helpers/is-empty-object.js
 @ ../../node_modules/@typedorm/core/src/classes/manager/batch-manager.js
 @ ../../node_modules/@typedorm/core/public-api.js
 @ ./src/handlers/hello/index.ts 11:21-57

WARNING in ../../node_modules/@typedorm/core/src/helpers/is-scalar-type.js 3:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ../../node_modules/@typedorm/core/src/classes/transformer/base-transformer.js
 @ ../../node_modules/@typedorm/core/src/classes/transformer/entity-transformer.js
 @ ../../node_modules/@typedorm/core/src/classes/manager/entity-manager.js
 @ ../../node_modules/@typedorm/core/public-api.js
 @ ./src/handlers/hello/index.ts 11:21-57

WARNING in ../../node_modules/@typedorm/core/src/helpers/is-used-for-primary-key.js 3:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ../../node_modules/@typedorm/core/src/classes/connection/connection.js
 @ ../../node_modules/@typedorm/core/public-api.js
 @ ./src/handlers/hello/index.ts 11:21-57

WARNING in ../../node_modules/@typedorm/core/src/helpers/parse-key.js 3:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ../../node_modules/@typedorm/core/src/classes/transformer/document-client-request-transformer.js
 @ ../../node_modules/@typedorm/core/src/classes/manager/entity-manager.js
 @ ../../node_modules/@typedorm/core/public-api.js
 @ ./src/handlers/hello/index.ts 11:21-57

WARNING in ../../node_modules/@typedorm/core/src/helpers/unparse-key.js 3:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ../../node_modules/@typedorm/core/src/classes/transformer/entity-transformer.js
 @ ../../node_modules/@typedorm/core/src/classes/manager/entity-manager.js
 @ ../../node_modules/@typedorm/core/public-api.js
 @ ./src/handlers/hello/index.ts 11:21-57
```

**Comment by mishabruml** [comment]
Seems related to #66 
I have tried bundling with serverless-bundle and get a different issue: 

```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module '@typedorm/common/src/decorators/attribute.decorator'",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '@typedorm/common/src/decorators/attribute.decorator'",
        "    at _loadUserApp (/var/runtime/UserFunction.js:202:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:242:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
        "    at Module.load (internal/modules/cjs/loader.js:950:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```

**Comment by mishabruml** [comment]
OK, had success. I changed my `tsconfig` `compilerOptions.module` settings from `ES6` to `CommonJS`

**Comment by whimzyLive** [comment]
@mishabruml 
Please checkout [this](https://github.com/typedorm/typedorm/issues/220#issuecomment-1072568635) for a suggested workaround until the release process is updated to publish modules in `esm` & `cjs` instead of `umd`

**Comment by whimzyLive** [comment]
Closing this as a duplicate to #220 . 
Please feel free to reopen, if the workaround suggested above does not work for you.

**Comment by mishabruml** [comment]
Hey @whimzyLive I gave up in the end and bundled with `esbuild`, explicitly excluding typedorm
