### ISSUE TITLE
NoSuchEntityExistsError despite TS compiling when calling EntityManager.create

### ISSUE THREAD

**Issue by mishabruml** [typedorm/typedorm#203]
Hey, thanks for an awesome library!

```typescript
/* eslint-disable new-cap */
import "reflect-metadata";
import { Attribute, Entity, Table } from "@typedorm/common";
import { createConnection, getEntityManager } from "@typedorm/core";
import { v4 } from "uuid";

@Entity({
  name: "AccountState",
  primaryKey: {
    partitionKey: "{{accountId}}",
  },
})
class AccountState {
  @Attribute({ unique: true })
  accountId!: string;

  @Attribute()
  flag!: boolean;

  constructor({ accountId, flag }: { accountId: string; flag: boolean }) {
    this.accountId = accountId;
    this.flag = flag;
  }
}

const accountStateTable = new Table({
  name: "AccountStateTable",
  partitionKey: "accountId",
});

createConnection({
  table: accountStateTable,
  entities: [AccountState],
});

(async () => {
  const accountId = v4();
  const accountState = new AccountState({ accountId, flag: true });
  const entityManager = getEntityManager();
  await entityManager.create<AccountState>(accountState); // works
  await entityManager.create<AccountState>({ accountId, flag: true }); // fails
})();
```

The above code compiles with no TS errors, but running it throws:

```bash
Error: No such entity named "Object" is known to TypeDORM, make sure it is declared at the connection creation time.
    at Connection.getEntityByTarget (/Users/mishabruml/packages/core/src/classes/connection/connection.ts:158:13)
    at DocumentClientRequestTransformer.toDynamoPutItem (/Users/mishabruml/packages/core/src/classes/transformer/document-client-request-transformer.ts:115:63)
    at EntityManager.<anonymous> (/Users/mishabruml/packages/core/src/classes/manager/entity-manager.ts:148:55)
    at Generator.next (<anonymous>)
    at /Users/mishabruml/*********
    at new Promise (<anonymous>)
    at __awaiter (/Users/mishabruml/******
    at EntityManager.create (/Users/mishabruml/******
    at /Users/mishabruml/******
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I think this problem could be solved with some more checks, maybe an `instanceof` typeguard here https://github.com/typedorm/typedorm/blob/9ae116dd042edaa1c151d00a29099a19df99ee58/packages/common/src/utils/get-entity-definition.ts#L8

Happy to make a PR?

Cheers,

Misha

**Comment by whimzyLive** [comment]
Hi @mishabruml 

Great find. PRs are always welcomed. 

Can I suggest that you follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) when you commit the code upstream? 
These commit messages are VERY important as they are used to figure out what will be the next release (patch, minor, major) as well as are used for generating the release notes.

I will try to also set up a contributing guide to the repo, sometime this week.

**Comment by mishabruml** [comment]
Hey @whimzyLive cool, thanks. Does the code I've linked to look like the right place to resolve this? 

RE: conventional commits, no probs. If desirable, its possible to enforce this via husky or similar. I can PR that too?
