### ISSUE TITLE
Cannot find module '@typedorm/common/public-api'

### ISSUE THREAD

**Issue by romcok** [typedorm/typedorm#225]
Hi,
I ran into a strange problem when using typedorm in lambda. I am using SST + CDK and esbuild to build functions. I added the `@anatine/esbuild-decorators` library for using decorators, but I think it would be a different error message for decorators. Here is the error message:

```json
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module '@typedorm/common/public-api'\nRequire stack:\n- /var/task/src/admin-api/root/rootMe.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '@typedorm/common/public-api'",
        "Require stack:",
        "- /var/task/src/admin-api/root/rootMe.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:202:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:242:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
        "    at Module.load (internal/modules/cjs/loader.js:950:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```

Any suggestions on where the problem might be? Here are the imports I am using:
```typescript
import { 
    BatchManager, 
    Connection, 
    createConnection, 
    EntityManager, 
    EntityManagerCountOptions, 
    EntityManagerCreateOptions, 
    EntityManagerDeleteOptions, 
    EntityManagerFindOneOptions, 
    EntityManagerFindOptions, 
    EntityManagerUpdateOptions, 
    ReadBatch, 
    TransactionManager } from "@typedorm/core"
import { EntityAttributes } from "@typedorm/common"
import { UpdateBody } from "@typedorm/core/src/classes/expression/update-body-type"
import { ScanManager, ScanManagerFindOptions } from "@typedorm/core/src/classes/manager/scan-manager"
import { MetadataOptions } from "@typedorm/core/src/classes/transformer/base-transformer"
```
Locally, everything works fine. Thanks 🙏

**Comment by whimzyLive** [comment]
@romcok 
There is already an issue tracked here for [fixing this](https://github.com/typedorm/typedorm/issues/220), basically, the core issue is that we are currently only publishing UMD modules, which doesn't go nicely with the bundlers. We have seen a similar issue happening with Webpack and Rollup and I guess the esBuild is no different. 

Until we are publishing all the modules in CJS/ESM, you will need to exclude @typedorm packages from the bundle and have them available as an external dependency in Lambda runtime.

**Comment by whimzyLive** [comment]
Closing this as an duplication of #220

**Comment by romcok** [comment]
Okay, just found it in other threads here. Thanks 🙏
