### ISSUE TITLE
typedorm with NestJS and serverless-framework

### ISSUE THREAD

**Issue by m-kotek** [typedorm/typedorm#293]
Hi!
I'm having trouble using typedorm with NestJS and Serverless-framework.

_Repo will be linked soon_

**What's the Problem?**
If the app is started with `serverless offline start` or `serverless invoke local -f main` the Lambda crashes.

At first I followed the instructions and only called `createConnection()` in `main.js`. If `const entityManager = getEntityManager()` now is called from `app.service.ts`'s constructor the console output is as follows: 

```
[Nest] 24576  - 23.11.2022, 19:36:20     LOG [NestFactory] Starting Nest application...
[Nest] 24576  - 23.11.2022, 19:36:20   ERROR [ExceptionHandler] No such connection with name "default" exists
✖ Lambda timeout.
``` 

Then I introduced and exported a variable `entityManager` in `main.ts`. After calling `createConnection()` I called `entityManager = getEntityManager()`. This leads to following outputs:

Output with `serverless offline start`
``` 
[Nest] 25733  - 23.11.2022, 19:47:11     LOG [NestFactory] Starting Nest application...
[Nest] 25733  - 23.11.2022, 19:47:11   ERROR [ExceptionHandler] 
✖ Lambda timeout.
``` 

Output with `serverless invoke local -f main`
``` 
[Nest] 26873  - 23.11.2022, 20:47:22     LOG [NestFactory] Starting Nest application... +2ms
[Nest] 26873  - 23.11.2022, 20:47:22   ERROR [ExceptionHandler]
TypeError
at Reflect.getMetadata (/home/mon/Desktop/api-master-serverless/node_modules/reflect-metadata/Reflect.js:354:23)
at DependenciesScanner.isInjectable (/home/mon/Desktop/api-master-serverless/node_modules/@nestjs/core/scanner.js:302:26)
at DependenciesScanner.insertModule (/home/mon/Desktop/api-master-serverless/node_modules/@nestjs/core/scanner.js:73:18)
at DependenciesScanner.scanForModules (/home/mon/Desktop/api-master-serverless/node_modules/@nestjs/core/scanner.js:34:43)
at DependenciesScanner.scan (/home/mon/Desktop/api-master-serverless/node_modules/@nestjs/core/scanner.js:27:20)
at async /home/mon/Desktop/api-master-serverless/node_modules/@nestjs/core/nest-factory.js:95:17
at async Function.asyncRun (/home/mon/Desktop/api-master-serverless/node_modules/@nestjs/core/errors/exceptions-zone.js:22:13)
at async NestFactoryStatic.initialize (/home/mon/Desktop/api-master-serverless/node_modules/@nestjs/core/nest-factory.js:94:13)
at async NestFactoryStatic.create (/home/mon/Desktop/api-master-serverless/node_modules/@nestjs/core/nest-factory.js:37:9)
at async bootstrap (/home/mon/Desktop/api-master-serverless/dist/main.js:33:17)
```

A part of `main.ts`:
``` 
const documentClient = new DocumentClientV3(new DynamoDBClient({}));

export const masterTable = new Table({
  name: 'master',
  partitionKey: 'PK',
  sortKey: 'SK',
});

export let entityManager: EntityManager = null;

async function bootstrap() {
  config.update({
    region: '--',
    accessKeyId: '--',
    secretAccessKey: '--',
    signatureVersion: '--',
  });

  createConnection({
    table: masterTable,
    name: 'default',
    entities: [Organization],
    documentClient,
  });

  entityManager = getEntityManager();

  const app = await NestFactory.create(AppModule);
  await app.listen(3000);
}

bootstrap();
``` 

Also I tried to `import 'reflect-metadata'` in 'index.ts`, `main.ts` and in both at the same time resulting in the same output.

Is it possible, that this has something to do with typedorm itself?
Thanks in advance and also for your great work!

**Comment by ekasprzyk** [comment]
It might not.  

I've been experimenting using the TypeDORM NestJS config plugin, which I can verify is working.

https://www.npmjs.com/package/@skypress/nestjs-dynamodb

Your issue might be that the server is starting out of order with the connection creation.  The library takes care of that.

e.g.
```
const table = new Table({
  // Redacted
});

@Module({
  imports: [
    TypeDormModule.forRoot({
      table,
      // entities: '**/*.entity.ts',
      entities: [Company],
      documentClient: new DocumentClientV3(new DynamoDBClient({})),
    }),
    CompaniesModule,
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

If that's not it, it might be because serverless offline isn't creating a DDB server and table and you may not be referring to AWS.

There's a serverless module for offline DDB, but you can also use docker to start your own.  We have done this for the previous ApolloServer version, so yell if you need help with that.
