### ISSUE TITLE
Missing decorator metadata on building with esbuild

### ISSUE THREAD

**Issue by whimzyLive** [typedorm/typedorm#88]
Decorator types are missing when trying to bundle using esbuild 
```
Cannot read property 'name' of undefined.
at 
let type = Reflect.getMetadata('design:type', target, propertyKey).name;
on file attribute.decorator.js
```

**Comment by whimzyLive** [comment]
esbuild does not have any plans on supporting tsc (emitDecoratorMetadata) flag, perhaps as a workaround, look into building a esbuild tsc plugin to do compilation for ts files containing decorators (a simple usage is described here)

https://github.com/thomaschaaf/esbuild-plugin-tsc

**Comment by whimzyLive** [comment]
for a workaround have a look at 

https://github.com/whimzyLive/ts-metadata-build

**Comment by mishabruml** [comment]
hey, I checked out https://github.com/whimzyLive/ts-metadata-build but I couldn't get the compiled js to run. 

Here is the compiled js 

```js
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __markAsModule = (target) => __defProp(target, "__esModule", {value: true});
var __commonJS = (callback, module2) => () => {
  if (!module2) {
    module2 = {exports: {}};
    callback(module2.exports, module2);
  }
  return module2.exports;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, {get: all[name], enumerable: true});
};
var __exportStar = (target, module2, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && key !== "default")
        __defProp(target, key, {get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable});
  }
  return target;
};
var __toModule = (module2) => {
  return __exportStar(__markAsModule(__defProp(module2 != null ? __create(__getProtoOf(module2)) : {}, "default", module2 && module2.__esModule && "default" in module2 ? {get: () => module2.default, enumerable: true} : {value: module2, enumerable: true})), module2);
};
var __decorate = (decorators, target, key, kind) => {
  var result = kind > 1 ? void 0 : kind ? __getOwnPropDesc(target, key) : target;
  for (var i = decorators.length - 1, decorator; i >= 0; i--)
    if (decorator = decorators[i])
      result = (kind ? decorator(target, key, result) : decorator(result)) || result;
  if (kind && result)
    __defProp(target, key, result);
  return result;
};

// node_modules/@typedorm/common/index.js
var require_common = __commonJS((exports2, module2) => {
  var __createBinding = exports2 && exports2.__createBinding || (Object.create ? function(o, m, k, k2) {
    if (k2 === void 0)
      k2 = k;
    Object.defineProperty(o, k2, {enumerable: true, get: function() {
      return m[k];
    }});
  } : function(o, m, k, k2) {
    if (k2 === void 0)
      k2 = k;
    o[k2] = m[k];
  });
  var __exportStar2 = exports2 && exports2.__exportStar || function(m, exports3) {
    for (var p in m)
      if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports3, p))
        __createBinding(exports3, m, p);
  };
  (function(factory) {
    if (typeof module2 === "object" && typeof module2.exports === "object") {
      var v = factory(require, exports2);
      if (v !== void 0)
        module2.exports = v;
    } else if (typeof define === "function" && define.amd) {
      define("@typedorm/common", ["require", "exports", "@typedorm/common/public-api", "@typedorm/common/private-api"], factory);
    }
  })(function(require2, exports3) {
    "use strict";
    Object.defineProperty(exports3, "__esModule", {value: true});
    __exportStar2(require2("@typedorm/common/public-api"), exports3);
    __exportStar2(require2("@typedorm/common/private-api"), exports3);
  });
});

// packages/package-a/org.entity.ts
var require_org_entity = __commonJS((exports2) => {
  __markAsModule(exports2);
  __export(exports2, {
    Org: () => Org
  });
  var import_common = __toModule(require_common());
  var Org = class {
  };
  __decorate([
    (0, import_common.Attribute)()
  ], Org.prototype, "id", 2);
  Org = __decorate([
    (0, import_common.Entity)({
      name: "org",
      primaryKey: {
        partitionKey: "{{id}}"
      }
    })
  ], Org);
});

// packages/package-b/branch.entity.ts
var require_branch_entity = __commonJS((exports2) => {
  __markAsModule(exports2);
  __export(exports2, {
    Branch: () => Branch
  });
  var import_common = __toModule(require_common());
  var Branch = class {
  };
  __decorate([
    (0, import_common.Attribute)()
  ], Branch.prototype, "id", 2);
  Branch = __decorate([
    (0, import_common.Entity)({
      name: "branch",
      primaryKey: {
        partitionKey: "{{id}}"
      }
    })
  ], Branch);
});

// lib/tsc/src/user.entity.js
var require_user_entity = __commonJS((exports2) => {
  "use strict";
  var __decorate2 = exports2 && exports2.__decorate || function(decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function")
      r = Reflect.decorate(decorators, target, key, desc);
    else
      for (var i = decorators.length - 1; i >= 0; i--)
        if (d = decorators[i])
          r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
  };
  var __metadata = exports2 && exports2.__metadata || function(k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function")
      return Reflect.metadata(k, v);
  };
  Object.defineProperty(exports2, "__esModule", {value: true});
  exports2.User = void 0;
  var common_1 = require_common();
  var User = class User {
  };
  __decorate2([
    common_1.Attribute(),
    __metadata("design:type", String)
  ], User.prototype, "id", void 0);
  User = __decorate2([
    common_1.Entity({
      name: "user",
      primaryKey: {
        partitionKey: "id"
      }
    })
  ], User);
  exports2.User = User;
});

// lib/tsc/src/index.js
"use strict";
Object.defineProperty(exports, "__esModule", {value: true});
var org_entity_1 = require_org_entity();
var branch_entity_1 = require_branch_entity();
var user_entity_1 = require_user_entity();
var user = new user_entity_1.User();
user.id = "user-1";
var org = new org_entity_1.Org();
org.id = "org-1";
var branch = new branch_entity_1.Branch();
branch.id = "branch-1";
console.log("User: ", user.id);
console.log("Org: ", org.id);
console.log("Branch: ", branch.id);
```

**Comment by mishabruml** [comment]
running `node lib/esbuild/bundle.js` on the above results in 

```
/Users/mishabruml/projects/ts-metadata-build/node_modules/@typedorm/common/src/decorators/attribute.decorator.js:17
            let type = Reflect.getMetadata('design:type', target, propertyKey).name;
                                                                              ^

TypeError: Cannot read property 'name' of undefined
    at /Users/mishabruml/projects/ts-metadata-build/node_modules/@typedorm/common/src/decorators/attribute.decorator.js:17:79
    at __decorate (/Users/mishabruml/projects/ts-metadata-build/lib/esbuild/bundle.js:34:24)
    at /Users/mishabruml/projects/ts-metadata-build/lib/esbuild/bundle.js:83:3
    at /Users/mishabruml/projects/ts-metadata-build/lib/esbuild/bundle.js:11:5
    at Object.<anonymous> (/Users/mishabruml/projects/ts-metadata-build/lib/esbuild/bundle.js:158:20)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
```
